data:
  raw_path: "data/raw/breast_cancer.csv"
  processed_path: "data/processed"
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"

preprocessing:
  target_column: "diagnosis"
  test_size: 0.2
  random_state: 42

model:
  model_path: "models/model"
  random_state: 42 